site_name: PySATL
site_url: !ENV [READTHEDOCS_CANONICAL_URL, 'https://pysatl.github.io/pysatl-criterion/en/']
site_description: PySATL is a free and open source statistics lib written in Python, designed to support all major researcher demands
repo_url: https://github.com/PySATL/pysatl-criterion
edit_uri: edit/main/docs/
use_directory_urls: True
nav:
    - Home: index.md
    - Criteria:
        - Goodness-of-fit:
            - Exponentiality:
                - Epps and Pulley: criteria/goodness-of-fit/exponentiality/epps_pulley_exp_criterion.md
                - Kolmogorov-Smirnov: criteria/goodness-of-fit/exponentiality/kolmogorov_smirnov_exp_criterion.md
                - Wong and Wong: criteria/goodness-of-fit/exponentiality/wong_wong_exp_criterion.md
                - WE: criteria/goodness-of-fit/exponentiality/we_exp_criterion.md
                - Ahsanullah: criteria/goodness-of-fit/exponentiality/ahsanullah_exp_criterion.md
                - Atkinson: criteria/goodness-of-fit/exponentiality/atkinson_exp_criterion.md
                - Cox and Oakes: criteria/goodness-of-fit/exponentiality/cox_oakes_exp_criterion.md
                - Cramer-von Mises: criteria/goodness-of-fit/exponentiality/cvm_exp_criterion.md
                - Deshpande: criteria/goodness-of-fit/exponentiality/deshpande_exp_criterion.md
                - Epstein: criteria/goodness-of-fit/exponentiality/epstein_exp_criterion.md
                - Frozini: criteria/goodness-of-fit/exponentiality/frozini_exp_criterion.md
                - Gini: criteria/goodness-of-fit/exponentiality/gini_exp_criterion.md
                - Gnedenko: criteria/goodness-of-fit/exponentiality/gnedenko_exp_criterion.md
                - Harris: criteria/goodness-of-fit/exponentiality/harris_exp_criterion.md
                - Hegazy1: criteria/goodness-of-fit/exponentiality/hegazy1_exp_criterion.md
                - Hegazy2: criteria/goodness-of-fit/exponentiality/hegazy2_exp_criterion.md
                - Holander-Proshan: criteria/goodness-of-fit/exponentiality/holander_proshan_exp_criterion.md
                - Kimber-Michael: criteria/goodness-of-fit/exponentiality/kimber_michael_exp_criterion.md
                - Kochar: criteria/goodness-of-fit/exponentiality/kochar_exp_criterion.md
                - Lorenz: criteria/goodness-of-fit/exponentiality/lorenz_exp_criterion.md
                - Moran: criteria/goodness-of-fit/exponentiality/moran_exp_criterion.md
                - Pietra: criteria/goodness-of-fit/exponentiality/pietra_exp_criterion.md
                - Shapiro-Wilk: criteria/goodness-of-fit/exponentiality/shapiro_wilk_exp_criterion.md
                - Rossberg: criteria/goodness-of-fit/exponentiality/rossberg_exp_criterion.md
                - Graph edges number: criteria/goodness-of-fit/exponentiality/graph_edges_number_exp_criterion.md
                - Graph max degree: criteria/goodness-of-fit/exponentiality/graph_max_degree_exp_criterion.md
            - Uniformity:
                - Kolmogorov-Smirnov: criteria/goodness-of-fit/uniformity/kolmogorov_smirnov_uniform_criterion.md
                - Anderson-Darling: criteria/goodness-of-fit/uniformity/anderson_darling_uniform_criterion.md
                - Cramer-von Mises: criteria/goodness-of-fit/uniformity/cvm_uniform_criterion.md
                - Lilliefors: criteria/goodness-of-fit/uniformity/lilliefors_uniform_criterion.md
                - Pearson chi-squared: criteria/goodness-of-fit/uniformity/chi2_pearson_uniform_criterion.md
                - Watson: criteria/goodness-of-fit/uniformity/watson_uniform_criterion.md
                - Kuiper: criteria/goodness-of-fit/uniformity/kuiper_uniform_criterion.md
                - Greenwood: criteria/goodness-of-fit/uniformity/greenwood_uniform_criterion.md
                - Bickel-Rosenblatt: criteria/goodness-of-fit/uniformity/bickel_rosenblatt_uniform_criterion.md
                - Zhang: criteria/goodness-of-fit/uniformity/zhang_uniform_criterion.md
                - Stein: criteria/goodness-of-fit/uniformity/stein_uniform_criterion.md
                - Censored Stein: criteria/goodness-of-fit/uniformity/censored_stein_uniform_criterion.md
                - Neyman smooth: criteria/goodness-of-fit/uniformity/neyman_smooth_uniform_criterion.md
                - Sherman: criteria/goodness-of-fit/uniformity/sherman_uniform_criterion.md
                - Quesenberry-Miller: criteria/goodness-of-fit/uniformity/quesenberry_miller_uniform_criterion.md
theme:
  name: material
  logo: "images/logo.jpeg"
  favicon: "images/logo.jpeg"
  custom_dir: "docs/overrides"
  features:
    - content.code.annotate
    - search.share
    - content.code.copy
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      primary: "blue grey"
      accent: "tear"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: "blue grey"
      accent: "tear"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - "stylesheets/ft.extra.css"
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.pathconverter
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_truly_sane_lists
extra:
  version:
    provider: mike
    alias: true
plugins:
  - search:
      enabled: true
  - mike:
      deploy_prefix: 'en'
      canonical_version: 'stable'
